apiVersion: integreatly.org/v1alpha1
kind: Redis
metadata:
  # name must be between 1-40 characters
  name: example-redis
spec:
  # i want my redis storage information output in a secret named example-redis-sec
  secretRef:
    name: example-redis-sec
  # i want a redis storage of a development-level tier
  tier: development
  # the type i want a redis storage
  type: REPLACE_ME
